In [2]:
'''
This is how you add multiline comment
and use '#' for single line comment

Bye
'''

"\nThis is how you add multiline comment\nand use '#' for single line comment\n\nBye\n"

# Python Tutorial  Single # markdown

## Welcome  double # for heading

- Datatypes  used dash for this

In [3]:
1+1

2

In [4]:
10**2 #10 square

100

In [5]:
10 * 'Str'

'StrStrStrStrStrStrStrStrStrStr'

In [6]:
type(1)

int

In [7]:
a = "Hello, World!"
print(len(a))

13


In [8]:
a = 1
print(type(a))


<class 'int'>


In [9]:

a = ['s',2,4]
print(type(a))

<class 'list'>


In [10]:
type(True)

bool

In [11]:
mystr = 'shalmali limbkar'
print(mystr.isalnum()) 
print(mystr.isalpha()) 
print(mystr.isdigit()) 
print(mystr.islower()) 
print(mystr.isupper()) 
print(mystr.isnumeric()) 
print(mystr.isdecimal()) 
print(mystr.endswith('r')) 
print(mystr.startswith('s'))
print(mystr.isspace())
print(mystr.istitle()) #if it has any capital?

False
False
False
True
False
False
False
True
True
False
False


In [12]:
True and True

True

In [13]:
True and False

False

In [14]:
True or False

True

In [15]:
False or False

False

## List

In [16]:
a = ['s',2,4]
print(type(a))

<class 'list'>


## Apend

In [17]:
a.append("akshay")

In [18]:
a

['s', 2, 4, 'akshay']

In [19]:
#Indexing in list starts with zero
a[1]

2

In [20]:
#to pick range from list
a[1:]

[2, 4, 'akshay']

In [21]:
a[1:3]

[2, 4]

In [22]:
a.append(["harami", "shal"]) #This will get appended as a new list. Nested list

In [23]:
a

['s', 2, 4, 'akshay', ['harami', 'shal']]

## Insert in list

In [24]:
a=['s', 2, 4, 'akshay', ['harami', 'shal']]
a.insert(1,"sufi")
a.append(["hello", "world"])
a

['s', 'sufi', 2, 4, 'akshay', ['harami', 'shal'], ['hello', 'world']]

## Extend method

In [25]:
a= [1,2,4,5,6]
a.extend([8,87]) #unlike append, I am adding as a list but getting added as a numbers only not the lIST
a

[1, 2, 4, 5, 6, 8, 87]

In [26]:
sum(a) #adding list elements

113

## Pop

In [27]:
a.pop()

87

In [28]:
a

[1, 2, 4, 5, 6, 8]

In [29]:
a.pop(0)
a

[2, 4, 5, 6, 8]

In [30]:
a.count(2) #Count the occurances of 2

1

In [31]:
len(a)

5

In [32]:
a.index #Index: returns the index of first occurance , start and end parameters are not necessary

<function list.index(value, start=0, stop=9223372036854775807, /)>

In [34]:
a.index(1)

ValueError: 1 is not in list

In [35]:
a.index(2)

0

In [36]:
b= [1,1,2,4,5,6,1]
b.index(1,1,6) #Find 1 starting from 1st index to 5th index. It will give the first occurance 

1

In [38]:
min(b)

1

In [39]:
max(b)

6

In [40]:
b*2 #this will append the list twice . will not multiply the each number from the list

[1, 1, 2, 4, 5, 6, 1, 1, 1, 2, 4, 5, 6, 1]

## SETS

In [41]:
SetVar = set()    #Defining sets
print(SetVar)
print(type(SetVar))

set()
<class 'set'>


In [42]:
set_var = {1,2,3,4,3,5}   #even though duplicate 3, it will not get printed 
set_var

{1, 2, 3, 4, 5}

In [43]:
set_var= {'akshay','shalmali','adu'}
print(set_var)
print(type(set_var))

{'adu', 'shalmali', 'akshay'}
<class 'set'>


In [45]:
#Indexing Set does not support any Indexing

#inbuilt functions

set_var= {'akshay','shalmali','adu'}
set_var.add('Hulk')                     #add function
print(set_var)



{'adu', 'shalmali', 'akshay', 'Hulk'}


In [46]:
set1= {'akshay','shalmali','adu'}
set2= {'akshay','shalmali','adu', 'sharri', 'vinit'}

set2.difference(set1)  #from set 2 , remove the matching with set 1, But this will not update the set2 permentantly.


{'sharri', 'vinit'}

In [47]:
set1= {'akshay','shalmali','adu'}
set2= {'akshay','shalmali','adu', 'sharri', 'vinit'}
set2.intersection(set1)

{'adu', 'akshay', 'shalmali'}

In [48]:

set2.difference_update(set1)  #this will update out set2 in real

In [49]:
set2


{'sharri', 'vinit'}

## Dictionary 

In [50]:
dic= {}
type(dic)
type(dict())

dict

In [51]:
my_dic ={"car1":"bmw","car2":"audi","car3":"porsche"}
my_dic

{'car1': 'bmw', 'car2': 'audi', 'car3': 'porsche'}

In [52]:
type(dict())

dict

In [53]:
my_dic['car1']    #with the help of key, data can be retrived

'bmw'

In [54]:
for x in my_dic:  # loop thr keys. By default it will loop thr keys
    print(x)

car1
car2
car3


In [55]:
for x in my_dic.values(): # loop thr values. 
    print(x)


bmw
audi
porsche


In [56]:
# loop thr Both keys and values.
for x in my_dic.items():
    print(x)


('car1', 'bmw')
('car2', 'audi')
('car3', 'porsche')


In [57]:
#adding items in Dictionary:
my_dic['car4'] = 'tata'
print(my_dic)

{'car1': 'bmw', 'car2': 'audi', 'car3': 'porsche', 'car4': 'tata'}


In [58]:
my_dic['car1']='Nissan'  #replacing value
my_dic

{'car1': 'Nissan', 'car2': 'audi', 'car3': 'porsche', 'car4': 'tata'}

## Nested Dictionary 

In [59]:
car1_model={'maruti alto':800}
car2_model={'audi': 2.0}
car3_model ={'porsche': 911}

car_type={'car1':car1_model,'car2':car2_model,'car3':car3_model}

print (car_type)

{'car1': {'maruti alto': 800}, 'car2': {'audi': 2.0}, 'car3': {'porsche': 911}}


In [60]:
##accessing the exact model number 800
print(car_type['car1'])

{'maruti alto': 800}


In [61]:
print(car_type['car1']['maruti alto'])


800


## Tuple

In [62]:
my_tuple= tuple()
print(type(my_tuple))

<class 'tuple'>


In [63]:
my_tuple= ('aa','bb','cc')
my_tuple

('aa', 'bb', 'cc')

In [64]:
my_tuple.index('aa')  #Indexing in tuple

0

In [65]:
my_tuple.count('bb')

1

# NumPy

In [67]:
#install numpy :
!pip install numpy
#conda install numpy

In [68]:
import numpy as np

In [69]:
my_lst=[1,2,3,4,5]    #this will convert your list into array
ar=np.array(my_lst)

In [70]:
type(my_lst)

list

In [71]:
type(ar)

numpy.ndarray

In [72]:
ar

array([1, 2, 3, 4, 5])

In [73]:
print(ar)

[1 2 3 4 5]


In [74]:
ar.shape   #one dimensional array 

(5,)

In [75]:
lst1=[1,2,3,8]
lst2=[3,4,5,8]
lst3=[6,7,8,4]
arr=np.array([lst1,lst2,lst3])
print(arr)  #double brackets means two dimensions, if 3D, 3 brackets would be there in output

[[1 2 3 8]
 [3 4 5 8]
 [6 7 8 4]]


In [76]:
arr.shape  #rows,column

(3, 4)

In [77]:
arr.reshape(4,3) #MULTIPLICATION MUST BE SAME TO RESHAPE TO ANY 

array([[1, 2, 3],
       [8, 3, 4],
       [5, 8, 6],
       [7, 8, 4]])

In [78]:
#Accessing the element ---- indexing starts from zero
arr=np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
arr[2]

3

In [80]:
lst1=[1,2,3,8]
lst2=[3,4,5,8]
lst3=[6,7,8,4]
arr=np.array([lst1,lst2,lst3])
print(arr)

[[1 2 3 8]
 [3 4 5 8]
 [6 7 8 4]]


In [81]:
arr[:,:]   #indexing all rows and all columns . As nothing is passed it will display all the records


array([[1, 2, 3, 8],
       [3, 4, 5, 8],
       [6, 7, 8, 4]])

In [82]:
arr[:,2:]

array([[3, 8],
       [5, 8],
       [8, 4]])

In [83]:
arr[0:2,0:2]

array([[1, 2],
       [3, 4]])

In [84]:
arr[1:,2:] #or arr[1:3,2:] Or arr[1:3,2:3]

array([[5, 8],
       [8, 4]])

In [85]:
arr=np.arange(0,10,step=2) #step for increment 
arr

array([0, 2, 4, 6, 8])

In [86]:
arr=np.linspace(1,10,50) #equally spaced array creation. 
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [87]:
##Copy funcation:

arr[3:]=100
arr

array([  1.        ,   1.18367347,   1.36734694, 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        ])

In [88]:
arr=np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
arr1=arr     ##copy
arr1

array([1, 2, 3, 4, 5, 6, 7, 8])

# READ from CSV, JSON, HTML Files etc

In [92]:
import pandas as pd
df= pd.read_csv('merc.csv')

In [93]:
df.head()

model  year  price transmission  mileage fuelType  tax   mpg  \
0        SLK  2005   5200    Automatic    63000   Petrol  325  32.1   
1    S Class  2017  34948    Automatic    27000   Hybrid   20  61.4   
2   SL CLASS  2016  49948    Automatic     6200   Petrol  555  28.0   
3    G Class  2016  61948    Automatic    16000   Petrol  325  30.4   
4    G Class  2016  73948    Automatic     4000   Petrol  325  30.1   

   engineSize  
0         1.8  
1         2.1  
2         5.5  
3         4.0  
4         4.0

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13119 entries, 0 to 13118
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         13119 non-null  object 
 1   year          13119 non-null  int64  
 2   price         13119 non-null  int64  
 3   transmission  13119 non-null  object 
 4   mileage       13119 non-null  int64  
 5   fuelType      13119 non-null  object 
 6   tax           13119 non-null  int64  
 7   mpg           13119 non-null  float64
 8   engineSize    13119 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 922.6+ KB


In [95]:
df.describe()  # when you use describe function , It only takes Float/Int values in the consideration and NOT the categorical feature. You can not find Mean, median etc of categorical values

year          price        mileage           tax           mpg  \
count  13119.000000   13119.000000   13119.000000  13119.000000  13119.000000   
mean    2017.296288   24698.596920   21949.559037    129.972178     55.155843   
std        2.224709   11842.675542   21176.512267     65.260286     15.220082   
min     1970.000000     650.000000       1.000000      0.000000      1.100000   
25%     2016.000000   17450.000000    6097.500000    125.000000     45.600000   
50%     2018.000000   22480.000000   15189.000000    145.000000     56.500000   
75%     2019.000000   28980.000000   31779.500000    145.000000     64.200000   
max     2020.000000  159999.000000  259000.000000    580.000000    217.300000   

         engineSize  
count  13119.000000  
mean       2.071530  
std        0.572426  
min        0.000000  
25%        1.800000  
50%        2.000000  
75%        2.100000  
max        6.200000

In [103]:
df['year'].value_counts().sort_values(ascending=False)

year
2019    4553
2017    2381
2016    1971
2018    1467
2015     991
2020     719
2014     491
2013     292
2012      57
2011      38
2010      38
2007      22
2009      17
2008      16
2004      13
2001      10
2002       9
2005       9
2006       8
2003       7
1998       4
2000       3
1997       1
1999       1
1970       1
Name: count, dtype: int64

In [105]:
df['year'].value_counts().sort_index()  #as Year is the index , you use .sort_index()

year
1970       1
1997       1
1998       4
1999       1
2000       3
2001      10
2002       9
2003       7
2004      13
2005       9
2006       8
2007      22
2008      16
2009      17
2010      38
2011      38
2012      57
2013     292
2014     491
2015     991
2016    1971
2017    2381
2018    1467
2019    4553
2020     719
Name: count, dtype: int64

In [106]:
df[df['year']>2019]  #only display year values greater than 2019

model  year  price transmission  mileage fuelType  tax   mpg  \
10        A Class  2020  32980    Automatic      606   Petrol  145  35.8   
11        A Class  2020  26980    Automatic     1000   Diesel  145  62.8   
33        A Class  2020  28128    Automatic     2563   Petrol  145  47.9   
38        C Class  2020  31790    Automatic     3500   Petrol  145  64.2   
57      GLE Class  2020  48995    Automatic     3000   Diesel  145  36.7   
...           ...   ...    ...          ...      ...      ...  ...   ...   
13053     A Class  2020  27995    Automatic     2500   Diesel  145  67.3   
13056   GLE Class  2020  58450    Automatic     1159   Diesel  150  32.8   
13113     C Class  2020  30999    Automatic     1000   Diesel  145  64.2   
13114     C Class  2020  35999    Automatic      500   Diesel  145  55.4   
13115     B Class  2020  24699    Automatic     2500   Diesel  145  55.4   

       engineSize  
10            2.0  
11            1.5  
33            1.3  
38            2.0  
57            2.0  
...           ...  
13053         1.5  
13056         2.9  
13113         2.0  
13114         2.0  
13115         2.0  

[719 rows x 9 columns]

In [107]:
from io import StringIO, BytesIO

In [108]:
data= ('col1,col2,col3\n'
      'x,y,1\n'
      'a,4,6\n'
      'c,d,55')

In [109]:
type(data)

str

In [110]:
pd.read_csv(StringIO(data))  #converting above str datatyep into the csv with the help of StringIO

col1 col2  col3
0    x    y     1
1    a    4     6
2    c    d    55

In [113]:
df = pd.read_csv(StringIO(data), usecols=['col1','col3']) 

In [114]:
df.to_csv('Testingtocsv.csv')

In [117]:

df = pd.read_csv(StringIO(data), dtype=object)
df

col1 col2 col3
0    x    y    1
1    a    4    6
2    c    d   55

In [118]:
df['col3'][0]

'1'

In [120]:
df['col3']   #in csv all the values are in the object as we have given dtype =object above. 

0     1
1     6
2    55
Name: col3, dtype: object

In [126]:
df=pd.read_csv(StringIO(data),dtype={'col1':object,'col2':object,'col3':int})  #we can specify the datatype for every column.
df

col1 col2  col3
0    x    y     1
1    a    4     6
2    c    d    55

In [125]:
df['col3']  #now the colum 3 is int

0     1
1     6
2    55
Name: col3, dtype: int32

In [128]:
df.dtypes  #check the datatypes 

col1    object
col2    object
col3     int32
dtype: object

In [132]:
data= ('index,a,b,c\n'
          '4,apple,bat,5.7\n'
          '8,orange,cow,10')


In [135]:
pd.read_csv(StringIO(data))

index       a    b     c
0      4   apple  bat   5.7
1      8  orange  cow  10.0

In [136]:
pd.read_csv(StringIO(data),index_col=0)  #we are making first column as index

a    b     c
index                   
4       apple  bat   5.7
8      orange  cow  10.0

In [137]:
pd.read_csv(StringIO(data),index_col=1)  #we are making second column as index

index    b     c
a                       
apple       4  bat   5.7
orange      8  cow  10.0

In [140]:
data= ('a,b,c\n'
          '4,apple,bat,\n'
          '8,orange,cow,')


In [141]:
pd.read_csv(StringIO(data)) #If strat is number it will automatically take it as index , because by default the datatype is null, so it follows the same order as given

a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [142]:
#to handle the above issue : Index_col
pd.read_csv(StringIO(data),index_col=False)

a       b    c
0  4   apple  bat
1  8  orange  cow

In [143]:
# combine usecols and Index_col
data= ('a,b,c\n'
          '4,apple,bat,\n'
          '8,orange,cow,')

In [144]:
pd.read_csv(StringIO(data),usecols=['b','c'],index_col= False)

b    c
0   apple  bat
1  orange  cow

In [147]:
# quoting and Escape Characters. Very useful in NLP

data= 'a,b\n"Hello, \\"Bob\\", nice to see you ",5'
data

'a,b\n"Hello, \\"Bob\\", nice to see you ",5'

In [146]:
pd.read_csv(StringIO(data),escapechar='\\')

a  b
0  Hello, "Bob", nice to see you   5

In [152]:
# URL to csv

df=pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item', sep='\t')  #tab separator file

HTTPError: HTTP Error 403: Forbidden

Instead of directly using pd.read_csv with a URL, you can use the requests library to fetch the data first and then read it with pd.read_csv. This might provide more detailed error messages if there's an issue with fetching the data.

In [153]:
import pandas as pd
import requests
from io import StringIO

url = 'https://download.bls.gov/pub/time.series/cu/cu.item'
response = requests.get(url)
if response.status_code == 200:
    data = response.text
    df = pd.read_csv(StringIO(data), sep='\t')
    # Now you can work with the DataFrame
else:
    print("Failed to fetch data from URL:", url)


Failed to fetch data from URL: https://download.bls.gov/pub/time.series/cu/cu.item


### Read Json to csv


In [158]:
Data = '''
[
  {
    "id": 1,
    "name": "Alice",
    "age": 30,
    "city": "New York"
  },
  {
    "id": 2,
    "name": "Bob",
    "age": 25,
    "city": "Los Angeles"
  },
  {
    "id": 3,
    "name": "Charlie",
    "age": 35,
    "city": "Chicago"
  }
]
'''   # 3 qoutes as 3 rows/records


In [173]:
df1 = pd.read_json(Data)
df1

C:\Users\shalm\AppData\Local\Temp\ipykernel_11004\672080300.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df1 = pd.read_json(Data)


id     name  age         city
0   1    Alice   30     New York
1   2      Bob   25  Los Angeles
2   3  Charlie   35      Chicago

In [160]:
nested_data = '''
{
  "students": [
    {
      "id": 1,
      "name": "Alice",
      "age": 20,
      "courses": ["Math", "Physics", "Chemistry"]
    },
    {
      "id": 2,
      "name": "Bob",
      "age": 22,
      "courses": ["History", "Literature"]
    },
    {
      "id": 3,
      "name": "Charlie",
      "age": 21,
      "courses": ["Computer Science", "Statistics"]
    }
  ]
}
'''


In [161]:
pd.read_json(nested_data)

C:\Users\shalm\AppData\Local\Temp\ipykernel_11004\760961894.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(nested_data)


students
0  {'id': 1, 'name': 'Alice', 'age': 20, 'courses...
1  {'id': 2, 'name': 'Bob', 'age': 22, 'courses':...
2  {'id': 3, 'name': 'Charlie', 'age': 21, 'cours...

In [168]:
# Load the nested JSON data into a DataFrame
df = pd.json_normalize(pd.read_json(nested_data)['students'])

df

C:\Users\shalm\AppData\Local\Temp\ipykernel_11004\1221251714.py:2: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.json_normalize(pd.read_json(nested_data)['students'])


id     name  age                         courses
0   1    Alice   20      [Math, Physics, Chemistry]
1   2      Bob   22           [History, Literature]
2   3  Charlie   21  [Computer Science, Statistics]

In [169]:
df = pd.json_normalize(pd.read_json(StringIO(nested_data))['students'])  #to remove above issue 
df

id     name  age                         courses
0   1    Alice   20      [Math, Physics, Chemistry]
1   2      Bob   22           [History, Literature]
2   3  Charlie   21  [Computer Science, Statistics]

you can achieve the same result by using the json.loads() function to load the nested JSON data into a Python dictionary, and then pass the dictionary directly to pd.json_normalize()

In [164]:
# Load the nested JSON data into a dictionary

import json

data_dict = json.loads(nested_data)

# Flatten the nested structure and load it into a DataFrame
df = pd.json_normalize(data_dict['students'])

print(df)

   id     name  age                         courses
0   1    Alice   20      [Math, Physics, Chemistry]
1   2      Bob   22           [History, Literature]
2   3  Charlie   21  [Computer Science, Statistics]


In [170]:
# convert Json to Csv

df.to_csv('student.csv')

In [176]:
# Convert Json into diffrent json format

df1



id     name  age         city
0   1    Alice   30     New York
1   2      Bob   25  Los Angeles
2   3  Charlie   35      Chicago

In [177]:
df1.to_json()

'{"id":{"0":1,"1":2,"2":3},"name":{"0":"Alice","1":"Bob","2":"Charlie"},"age":{"0":30,"1":25,"2":35},"city":{"0":"New York","1":"Los Angeles","2":"Chicago"}}'

In [181]:
df1.to_json(orient='records')  # making it rows, otherwise default it will take key value pair. 

'[{"id":1,"name":"Alice","age":30,"city":"New York"},{"id":2,"name":"Bob","age":25,"city":"Los Angeles"},{"id":3,"name":"Charlie","age":35,"city":"Chicago"}]'

In [180]:
df1.to_json(orient='columns')    # making it columns 

'{"id":{"0":1,"1":2,"2":3},"name":{"0":"Alice","1":"Bob","2":"Charlie"},"age":{"0":30,"1":25,"2":35},"city":{"0":"New York","1":"Los Angeles","2":"Chicago"}}'

#### Orient will be used in app development or front end development. You will collect this orient result and give it to front end 

### Read HTML content

This is a web scrapping technique

In [182]:
url = 'https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/'

In [183]:
import requests

url = "https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"

# Send a GET request to the URL
response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Get the HTML content from the response
    html_content = response.text
    print(html_content)  # Print or process the HTML content as needed
else:
    print("Failed to fetch HTML content from the URL:", url)


<!DOCTYPE html>
<html lang="en-US">

<head>
<!-- Title and Meta Description -->
    <title>FDIC: Failed Bank List</title>
    <meta property="og:title" content="FDIC: Failed Bank List" />

    <meta name="description" content="Look up information on failed banks, including how your accounts and loans are affected and how vendors can file claims against receivership." />
    <meta property="og:description" content="Look up information on failed banks, including how your accounts and loans are affected and how vendors can file claims against receivership." />

    <link rel="canonical" href="https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/" />
    <meta property="og:url" content="https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/" />

    <!-- Basic Page Needs -->
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />

<!-- Share image -->
<meta
  property="og:image"
  content="https://www.fdic.gov/assets/images/

In [186]:
dfs= pd.read_html(html_content)
dfs

C:\Users\shalm\AppData\Local\Temp\ipykernel_11004\3938689800.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  dfs= pd.read_html(html_content)


[                         Bank NameBank       CityCity StateSt  CertCert  \
 0                        Citizens Bank       Sac City      IA      8758   
 1             Heartland Tri-State Bank        Elkhart      KS     25851   
 2                  First Republic Bank  San Francisco      CA     59017   
 3                       Signature Bank       New York      NY     57053   
 4                  Silicon Valley Bank    Santa Clara      CA     24735   
 ..                                 ...            ...     ...       ...   
 563                 Superior Bank, FSB       Hinsdale      IL     32646   
 564                Malta National Bank          Malta      OH      6629   
 565    First Alliance Bank & Trust Co.     Manchester      NH     34264   
 566  National State Bank of Metropolis     Metropolis      IL      3815   
 567                   Bank of Honolulu       Honolulu      HI     21029   
 
                    Acquiring InstitutionAI Closing DateClosing  FundFund  
 0        

If the HTML content is not being parsed correctly into tables using pd.read_html(), it could be due to various reasons such as malformed HTML or the tables being represented in a non-standard format.

In such cases, you might need to inspect the HTML content and manually extract the tables using libraries like BeautifulSoup.

In [187]:
from bs4 import BeautifulSoup
import pandas as pd
import requests

url = "https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"

# Send a GET request to the URL
response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Get the HTML content from the response
    html_content = response.text
    
    # Parse the HTML content using BeautifulSoup
    soup = BeautifulSoup(html_content, 'html.parser')
    
    # Find all tables in the HTML content
    tables = soup.find_all('table')
    
    # Iterate through each table and convert it to a DataFrame
    dfs = []
    for table in tables:
        df = pd.read_html(str(table))[0]  # Convert the table to a DataFrame
        dfs.append(df)
    
    # Now 'dfs' contains a list of DataFrames, each representing a table found in the HTML content
    # You can access and process each DataFrame as needed
    for i, df in enumerate(dfs):
        print(f"Table {i + 1}:")
        print(df)
        print("=" * 50)
else:
    print("Failed to fetch HTML content from the URL:", url)


Table 1:
                         Bank NameBank       CityCity StateSt  CertCert  \
0                        Citizens Bank       Sac City      IA      8758   
1             Heartland Tri-State Bank        Elkhart      KS     25851   
2                  First Republic Bank  San Francisco      CA     59017   
3                       Signature Bank       New York      NY     57053   
4                  Silicon Valley Bank    Santa Clara      CA     24735   
..                                 ...            ...     ...       ...   
563                 Superior Bank, FSB       Hinsdale      IL     32646   
564                Malta National Bank          Malta      OH      6629   
565    First Alliance Bank & Trust Co.     Manchester      NH     34264   
566  National State Bank of Metropolis     Metropolis      IL      3815   
567                   Bank of Honolulu       Honolulu      HI     21029   

                   Acquiring InstitutionAI Closing DateClosing  FundFund  
0              

C:\Users\shalm\AppData\Local\Temp\ipykernel_11004\1917320656.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]  # Convert the table to a DataFrame


In [188]:
import pandas as pd

url = "https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"

# Read tables directly from the URL
dfs = pd.read_html(url)

# Check if any tables were found
if len(dfs) > 0:
    # Print each DataFrame
    for i, df in enumerate(dfs):
        print(f"Table {i + 1}:")
        print(df)
        print("=" * 50)
else:
    print("No tables found on the webpage.")


Table 1:
                         Bank NameBank       CityCity StateSt  CertCert  \
0                        Citizens Bank       Sac City      IA      8758   
1             Heartland Tri-State Bank        Elkhart      KS     25851   
2                  First Republic Bank  San Francisco      CA     59017   
3                       Signature Bank       New York      NY     57053   
4                  Silicon Valley Bank    Santa Clara      CA     24735   
..                                 ...            ...     ...       ...   
563                 Superior Bank, FSB       Hinsdale      IL     32646   
564                Malta National Bank          Malta      OH      6629   
565    First Alliance Bank & Trust Co.     Manchester      NH     34264   
566  National State Bank of Metropolis     Metropolis      IL      3815   
567                   Bank of Honolulu       Honolulu      HI     21029   

                 Acquiring InstitutionAI Closing DateClosing  FundFund  
0              Io

In [190]:
df

Bank NameBank       CityCity StateSt  CertCert  \
0                        Citizens Bank       Sac City      IA      8758   
1             Heartland Tri-State Bank        Elkhart      KS     25851   
2                  First Republic Bank  San Francisco      CA     59017   
3                       Signature Bank       New York      NY     57053   
4                  Silicon Valley Bank    Santa Clara      CA     24735   
..                                 ...            ...     ...       ...   
563                 Superior Bank, FSB       Hinsdale      IL     32646   
564                Malta National Bank          Malta      OH      6629   
565    First Alliance Bank & Trust Co.     Manchester      NH     34264   
566  National State Bank of Metropolis     Metropolis      IL      3815   
567                   Bank of Honolulu       Honolulu      HI     21029   

                 Acquiring InstitutionAI Closing DateClosing  FundFund  
0              Iowa Trust & Savings Bank    November 3, 2023     10545  
1                 Dream First Bank, N.A.       July 28, 2023     10544  
2              JPMorgan Chase Bank, N.A.         May 1, 2023     10543  
3                    Flagstar Bank, N.A.      March 12, 2023     10540  
4    First–Citizens Bank & Trust Company      March 10, 2023     10539  
..                                   ...                 ...       ...  
563                Superior Federal, FSB       July 27, 2001      6004  
564                    North Valley Bank         May 3, 2001      4648  
565  Southern New Hampshire Bank & Trust    February 2, 2001      4647  
566              Banterra Bank of Marion   December 14, 2000      4646  
567                   Bank of the Orient    October 13, 2000      4645  

[568 rows x 7 columns]

In [192]:
url_mcc = 'https://en.wikipedia.org/wiki/Mobile_country_code'
dfs =pd.read_html(url_mcc,match='Country',header=0)


In [194]:
dfs

[     Mobile country code                                    Country ISO 3166  \
 0                    289                                 A Abkhazia    GE-AB   
 1                    412                                Afghanistan       AF   
 2                    276                                    Albania       AL   
 3                    603                                    Algeria       DZ   
 4                    544  American Samoa (United States of America)       AS   
 ..                   ...                                        ...      ...   
 247                  452                                    Vietnam       VN   
 248                  543                        W Wallis and Futuna       WF   
 249                  421                                    Y Yemen       YE   
 250                  645                                   Z Zambia       ZM   
 251                  648                                   Zimbabwe       ZW   
 
                          

In [198]:
dfs[0]  #convert first row into header

Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 6 columns]

### reading from EXCEL


In [200]:
df_excel = pd.read_excel('smartphones.xlsx')

In [201]:
df_excel

Name        OS  Capacity  Ram  Weight    Company  inch
0  Galaxy S8   Android        64    4   149.0    Samsung   5.8
1  Lumia 950  windows         32    3   150.0  Microsoft   5.2
2  Xpreia L1   Android        16    2   180.0       Sony   5.5
3  iphone 7        ios       128    2   138.0      Apple   4.7
4    U Ultra   Android        64    4   170.0        HTC   5.7
5  Galaxy S5   Android        16    2   145.0    Samsung   5.1
6  iphone 5s       ios        32    1   112.0      Apple   4.0
7    Moto G5   Android        16    3   144.5   Motorola   5.0
8     Pixel    Android       128    4   143.0     Google   5.0

## Pickling : This is imp

all pandas objects are equipped with to_pickle methods which use Python's cPickle module to save data structures to disk using pickel formal 

mostly all the machine learning algorithms are converted into pickle and then deployed on the cloud server . also ,, these pickles are integrated with front end 

In [202]:
df_excel.to_pickle('df_excel')

In [207]:
dfE=pd.read_pickle('df_excel')   #df_excel is stored in files 

In [205]:
dfE

Name        OS  Capacity  Ram  Weight    Company  inch
0  Galaxy S8   Android        64    4   149.0    Samsung   5.8
1  Lumia 950  windows         32    3   150.0  Microsoft   5.2
2  Xpreia L1   Android        16    2   180.0       Sony   5.5
3  iphone 7        ios       128    2   138.0      Apple   4.7
4    U Ultra   Android        64    4   170.0        HTC   5.7
5  Galaxy S5   Android        16    2   145.0    Samsung   5.1
6  iphone 5s       ios        32    1   112.0      Apple   4.0
7    Moto G5   Android        16    3   144.5   Motorola   5.0
8     Pixel    Android       128    4   143.0     Google   5.0

In [206]:
type(dfE)

pandas.core.frame.DataFrame

Pickling in Python refers to the process of serializing and deserializing Python objects into a byte stream. The serialized byte stream can then be saved to a file or transferred over a network, and later deserialized to reconstruct the original Python objects. This process is often used for data persistence, inter-process communication, or storing complex data structures.

Here's why pickling is useful in Python:

#### Data Persistence:
Pickling allows you to save the state of Python objects to disk. This can be useful for saving the state of a program between sessions or for caching expensive computations.
###### Example :
Pickling is like taking a snapshot of your Python objects and saving them to a file. This allows you to remember what your objects look like, even after your program has finished running. It's like saving a game so you can continue from where you left off later

#### Inter-Process Communication:
Pickling enables you to pass Python objects between different processes or even different machines. This is useful in distributed computing environments or when implementing inter-process communication mechanisms.
###### Example :
 Imagine you have two friends who speak different languages. Pickling is like putting a message in a box that both of them can understand. You can send this box between them, and they can open it to see what the message says.

#### Complex Data Structures:
Python's pickle module can handle complex data structures, including custom objects, nested lists, dictionaries, and more. It provides a convenient way to serialize and deserialize these structures without having to manually convert them into a format suitable for storage or transmission.
###### Example :
Pickling is like packing up a bunch of toys into a box. You can have all kinds of toys – big ones, small ones, even ones that you made yourself. Pickling helps you pack them neatly so you can store them away or send them to someone else

#### Cross-Language Compatibility:
Pickle files can be read and written by other programming languages, such as C++ or Java, using libraries or modules that support the pickle protocol. This allows for interoperability between Python and other languages.
###### Example :
Pickling is like using a secret code that only you and your friends know. Even if your friends speak different languages, they can still understand the secret code and use it to send messages back and forth.

Overall, pickling provides a convenient and efficient way to store, transfer, and reconstruct Python objects, making it a valuable tool for many use cases in Python programming. pickling is a way to save and share your Python objects easily, no matter how complex they are or what languages your friends speak. It's like putting things in a box so you can use them later or share them with others.